### ISSUE TITLE
一个图书管理界面，可以实现增删改查

### ISSUE THREAD

**Issue by xing393939** [xing393939/autogen-vue-code#10]
.

**Comment by xing393939** [comment]
x Build failed in 370ms
error during build:
Error: [vite]: Rollup failed to resolve import "uuid" from "/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/src/Preview.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:67589:27)
    at onRollupWarning (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:67617:9)
    at onwarn (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:67321:13)
    at file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:18351:13
    at Object.logger [as onLog] (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:19999:9)
    at ModuleLoader.handleInvalidResolvedId (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:18941:26)
    at file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:18899:26

**Comment by xing393939** [comment]
[Preview UI](https://xing393939.github.io/autogen-vue-code/58)
