### ISSUE TITLE
a tuckshop management website

### ISSUE THREAD

**Issue by xing393939** [xing393939/autogen-vue-code#15]
.

**Comment by xing393939** [comment]
x Build failed in 2.51s
error during build:
Error: [vite:load-fallback] Could not load /home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/src/components/ui (imported by src/Preview.vue): EISDIR: illegal operation on a directory, read

**Comment by xing393939** [comment]
```
x Build failed in 1.17s
error during build:
RollupError: Could not resolve "./components/ui" from "src/Preview.vue"
file: /home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/src/Preview.vue
    at getRollupError (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at ModuleLoader.handleInvalidResolvedId (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:18939:24)
    at file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:18899:26

```

**Comment by xing393939** [comment]
[Preview UI](https://xing393939.github.io/autogen-vue-code/102)
