### ISSUE TITLE
a fake analytics dashboard

### ISSUE THREAD

**Issue by xing393939** [xing393939/autogen-vue-code#20]

**Comment by xing393939** [comment]
x Build failed in 593ms
error during build:
Error: [vite]: Rollup failed to resolve import "@nivo/line" from "/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/src/Preview.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/vite/dist/node/chunks/dep-_QLjGPdL.js:67601:27)
    at onRollupWarning (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/vite/dist/node/chunks/dep-_QLjGPdL.js:67629:9)
    at onwarn (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/vite/dist/node/chunks/dep-_QLjGPdL.js:67333:13)
    at file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:18351:13
    at Object.logger [as onLog] (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:19999:9)
    at ModuleLoader.handleInvalidResolvedId (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:18941:26)
    at file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:18899:26

**Comment by xing393939** [comment]
x Build failed in 564ms
error during build:
SyntaxError: Attribute name cannot contain U+0022 ("), U+0027 ('), and U+003C (<).
    at createCompilerError (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:1325:17)
    at Object.emitError [as onerr] (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:2794:5)
    at Tokenizer.stateInAttrName (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:818:16)
    at Tokenizer.parse (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:1067:16)
    at Object.baseParse (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:2826:13)
    at Object.parse (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.prod.js:633:23)
    at Object.parse$2 [as parse] (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:1853:24)
    at createDescriptor (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@vitejs/plugin-vue/dist/index.mjs:74:43)
    at transformMain (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@vitejs/plugin-vue/dist/index.mjs:2319:34)
    at Object.transform (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@vitejs/plugin-vue/dist/index.mjs:2869:16)

**Comment by xing393939** [comment]
[Preview UI](https://xing393939.github.io/autogen-vue-code/74)

**Comment by xing393939** [comment]
```
x Build failed in 582ms
error during build:
Error: [vite]: Rollup failed to resolve import "@nivo/line" from "/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/src/Preview.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/vite/dist/node/chunks/dep-_QLjGPdL.js:67601:27)
    at onRollupWarning (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/vite/dist/node/chunks/dep-_QLjGPdL.js:67629:9)
    at onwarn (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/vite/dist/node/chunks/dep-_QLjGPdL.js:67333:13)
    at file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:18351:13
    at Object.logger [as onLog] (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:19999:9)
    at ModuleLoader.handleInvalidResolvedId (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:18941:26)
    at file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:18899:26

```

**Comment by xing393939** [comment]
[Preview UI](https://xing393939.github.io/autogen-vue-code/101)
