### ISSUE TITLE
个人博客网页

### ISSUE THREAD

**Issue by xing393939** [xing393939/autogen-vue-code#22]

**Comment by xing393939** [comment]
x Build failed in 557ms
error during build:
SyntaxError: [vite:vue] [vue/compiler-sfc] Identifier 'AspectRatio' has already been declared. (12:9)

/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/src/Preview.vue
10 |  import { Switch } from "@/components/ui/switch";
11 |  import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
12 |  import { AspectRatio } from "@/components/ui/aspect-ratio";
   |           ^
13 |  import { ArrowRight } from "lucide-vue-next";
14 |  
file: /home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/src/Preview.vue:12:9
    at constructor (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:353:19)
    at Parser.raise (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:3277:19)
    at ScopeHandler.checkRedeclarationInScope (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:1491:19)
    at ScopeHandler.declareName (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:1457:12)
    at Parser.declareNameFromIdentifier (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:7348:16)
    at Parser.checkIdentifier (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:7344:12)
    at Parser.checkLVal (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:7290:12)
    at Parser.finishImportSpecifier (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:13717:10)
    at Parser.parseImportSpecifier (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:13881:17)
    at Parser.parseNamedImportSpecifiers (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:13860:36)

**Comment by xing393939** [comment]
x Build failed in 564ms
error during build:
SyntaxError: [vite:vue] [vue/compiler-sfc] Identifier 'Alert' has already been declared. (19:9)

/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/src/Preview.vue
17 |  import { Textarea } from "@/components/ui/textarea";
18 |  import { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectTrigger, SelectValue } from "@/components/ui/select";
19 |  import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
   |           ^
20 |  import { Button } from "@/components/ui/button";
21 |  import { useToast } from "@/components/ui/toast/use-toast";
file: /home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/src/Preview.vue:19:9
    at constructor (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:353:19)
    at Parser.raise (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:3277:19)
    at ScopeHandler.checkRedeclarationInScope (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:1491:19)
    at ScopeHandler.declareName (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:1457:12)
    at Parser.declareNameFromIdentifier (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:7348:16)
    at Parser.checkIdentifier (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:7344:12)
    at Parser.checkLVal (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:7290:12)
    at Parser.finishImportSpecifier (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:13717:10)
    at Parser.parseImportSpecifier (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:13881:17)
    at Parser.parseNamedImportSpecifiers (/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/@babel/parser/lib/index.js:13860:36)

**Comment by xing393939** [comment]
src/Preview.vue (12:131): Error when using sourcemap for reporting an error: Can't resolve original location of error.
src/Preview.vue (12:131): "NavigationMenuViewport" is not exported by "src/components/ui/navigation-menu/index.js", imported by "src/Preview.vue".

**Comment by xing393939** [comment]
src/Preview.vue (13:131): Error when using sourcemap for reporting an error: Can't resolve original location of error.
x Build failed in 2.77s
error during build:
RollupError: src/Preview.vue (13:131): "NavigationMenuViewport" is not exported by "src/components/ui/navigation-menu/index.js", imported by "src/Preview.vue".
file: /home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/src/Preview.vue:13:131
11: const _hoisted_5 = /*#__PURE__*/_createElementVNode("p", null, "Discover insightful articles and thought-provoking discussions.", -1)
12: 
13: import { NavigationMenu, NavigationMenuContent, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger, Navigation...
                                                                                                                                       ^
14: import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
15: import { Button } from "@/components/ui/button";
    at getRollupError (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at Module.error (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:13688:16)
    at Module.traceVariable (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:14136:29)
    at ModuleScope.findVariable (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:11817:39)
    at ChildScope.findVariable (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:6037:38)
    at FunctionScope.findVariable (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:6037:38)
    at FunctionBodyScope.findVariable (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:6037:38)
    at ReturnValueScope.findVariable (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:6037:38)
    at FunctionBodyScope.findVariable (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:6037:38)

**Comment by xing393939** [comment]
[Preview UI](https://xing393939.github.io/autogen-vue-code/90)
