### ISSUE TITLE
生成一个登陆界、home页面、我的页面，要求用路由可以跳到每一个页面，底部导航栏，同时要保存用户登陆凭证，每次获取数据都要带上凭证

### ISSUE THREAD

**Issue by nlmayday** [xing393939/autogen-vue-code#45]
生成一个登陆界、home页面、我的页面，要求用路由可以跳到每一个页面，底部导航栏，同时要保存用户登陆凭证，每次获取数据都要带上凭证

**Comment by xing393939** [comment]
```
x Build failed in 638ms
error during build:
[vite]: Rollup failed to resolve import "vue-router" from "/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/src/Preview.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/.deno/vite@5.3.3/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:65881:17)
    at onRollupWarning (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/.deno/vite@5.3.3/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:65916:5)
    at onwarn (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/.deno/vite@5.3.3/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:65576:7)
    at file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/.deno/rollup@4.18.1/node_modules/rollup/dist/es/shared/node-entry.js:18483:13
    at Object.logger [as onLog] (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/.deno/rollup@4.18.1/node_modules/rollup/dist/es/shared/node-entry.js:20131:9)
    at ModuleLoader.handleInvalidResolvedId (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/.deno/rollup@4.18.1/node_modules/rollup/dist/es/shared/node-entry.js:19073:26)
    at file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/.deno/rollup@4.18.1/node_modules/rollup/dist/es/shared/node-entry.js:19031:26

```
