### ISSUE TITLE
An orders dashboard with a sidebar.

### ISSUE THREAD

**Issue by xing393939** [xing393939/autogen-vue-code#8]

**Comment by xing393939** [comment]
[Preview UI](https://xing393939.github.io/autogen-vue-code/46)

**Comment by xing393939** [comment]
src/Preview.vue (11:131): Error when using sourcemap for reporting an error: Can't resolve original location of error.
[31mx[39m Build failed in 2.68s
[31merror during build:
RollupError: [31msrc/Preview.vue (11:131): "NavigationMenuViewport" is not exported by "src/components/ui/navigation-menu/index.js", imported by "src/Preview.vue".[31m
file: [36m/home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/src/Preview.vue:11:131[31m
[33m 9: }, null, -1)
10: 
11: import { NavigationMenu, NavigationMenuContent, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger, Navigation...
                                                                                                                                       ^
12: import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
13: import { AspectRatio } from "@/components/ui/aspect-ratio";[31m
    at getRollupError (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at Module.error (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:13688:16)
    at Module.traceVariable (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:14136:29)
    at ModuleScope.findVariable (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:11817:39)
    at ChildScope.findVariable (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:6037:38)
    at FunctionScope.findVariable (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:6037:38)
    at FunctionBodyScope.findVariable (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:6037:38)
    at ReturnValueScope.findVariable (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:6037:38)
    at FunctionBodyScope.findVariable (file:///home/runner/work/autogen-vue-code/autogen-vue-code/vue-preview-ui/node_modules/rollup/dist/es/shared/node-entry.js:6037:38)[39m
